"""Add page_number and source_text to InvoiceItem

Revision ID: 495cb58d106e
Revises: ea0253a23fb0
Create Date: 2026-09-16 21:25:38.754319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495cb58d106e'
down_revision: Union[str, None] = 'ea0253a23fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('invoice_items', sa.Column('source_text', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'source_text')
    op.drop_column('invoice_items', 'page_number')
    # ### end Alembic commands ###
