"""initial_schema

Revision ID: ea0253a23fb0
Revises: 
Create Date: 2026-09-08 21:13:39.788505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea0253a23fb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('vendor_tax_id', sa.String(length=100), nullable=True),
    sa.Column('po_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('grand_total >= 0', name='ck_po_grand_total_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number', 'vendor_name', name='uq_po_number_vendor')
    )
    op.create_index('ix_purchase_orders_po_number', 'purchase_orders', ['po_number'], unique=False)
    op.create_index('ix_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.create_index('ix_purchase_orders_vendor_name', 'purchase_orders', ['vendor_name'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('vendor_tax_id', sa.String(length=100), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('grand_total >= 0', name='ck_invoice_grand_total_non_negative'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_name', 'invoice_number', name='uq_invoice_vendor_number')
    )
    op.create_index('ix_invoices_dup_detection', 'invoices', ['vendor_name', 'invoice_date', 'grand_total'], unique=False)
    op.create_index('ix_invoices_invoice_number', 'invoices', ['invoice_number'], unique=False)
    op.create_index('ix_invoices_po_number', 'invoices', ['po_number'], unique=False)
    op.create_index('ix_invoices_purchase_order_id', 'invoices', ['purchase_order_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_index('ix_invoices_vendor_name', 'invoices', ['vendor_name'], unique=False)
    op.create_table('purchase_order_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('normalized_description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_po_item_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_po_item_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id', 'line_number', name='uq_po_item_line')
    )
    op.create_index('ix_po_items_po_id', 'purchase_order_items', ['purchase_order_id'], unique=False)
    op.create_table('audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audits_invoice_id', 'audits', ['invoice_id'], unique=False)
    op.create_index('ix_audits_purchase_order_id', 'audits', ['purchase_order_id'], unique=False)
    op.create_index('ix_audits_status', 'audits', ['status'], unique=False)
    op.create_table('invoice_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_documents_hash', 'invoice_documents', ['document_hash'], unique=False)
    op.create_index('ix_invoice_documents_invoice_id', 'invoice_documents', ['invoice_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('normalized_description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_inv_item_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_inv_item_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'line_number', name='uq_invoice_item_line')
    )
    op.create_index('ix_invoice_items_invoice_id', 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('invoice_line_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_item_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('quantity_invoiced', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('invoiced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_invoiced > 0', name='ck_ledger_quantity_positive'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['purchase_order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_invoice_id', 'invoice_line_ledger', ['invoice_id'], unique=False)
    op.create_index('ix_ledger_po_item_id', 'invoice_line_ledger', ['purchase_order_item_id'], unique=False)
    op.create_index('ix_ledger_po_item_invoice', 'invoice_line_ledger', ['purchase_order_item_id', 'invoice_id'], unique=False)
    op.create_table('audit_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('field_path', sa.String(length=300), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_corrections_audit_id', 'audit_corrections', ['audit_id'], unique=False)
    op.create_index('ix_audit_corrections_invoice_id', 'audit_corrections', ['invoice_id'], unique=False)
    op.create_table('invoice_extractions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('model_provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('raw_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_extraction', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['invoice_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoice_extractions_document_id', 'invoice_extractions', ['document_id'], unique=False)
    op.create_index('ix_invoice_extractions_invoice_id', 'invoice_extractions', ['invoice_id'], unique=False)
    op.create_table('reconciliation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('invoice_subtotal', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('po_subtotal', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('invoice_tax', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('po_tax', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('invoice_discount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('po_discount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('invoice_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('po_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('difference_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('difference_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('overall_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_id')
    )
    op.create_index('ix_reconciliation_results_audit_id', 'reconciliation_results', ['audit_id'], unique=False)
    op.create_index('ix_reconciliation_results_status', 'reconciliation_results', ['overall_status'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_result_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expected_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('difference_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('difference_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('financial_impact', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('rule_triggered', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_result_id'], ['reconciliation_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anomalies_reconciliation_result_id', 'anomalies', ['reconciliation_result_id'], unique=False)
    op.create_index('ix_anomalies_severity', 'anomalies', ['severity'], unique=False)
    op.create_index('ix_anomalies_status', 'anomalies', ['status'], unique=False)
    op.create_index('ix_anomalies_type', 'anomalies', ['type'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('anomaly_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('field_path', sa.String(length=300), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.String(length=500), nullable=True),
    sa.Column('actual_value', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['invoice_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_anomaly_id', 'evidence', ['anomaly_id'], unique=False)
    op.create_index('ix_evidence_document_id', 'evidence', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_document_id', table_name='evidence')
    op.drop_index('ix_evidence_anomaly_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_anomalies_type', table_name='anomalies')
    op.drop_index('ix_anomalies_status', table_name='anomalies')
    op.drop_index('ix_anomalies_severity', table_name='anomalies')
    op.drop_index('ix_anomalies_reconciliation_result_id', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('ix_reconciliation_results_status', table_name='reconciliation_results')
    op.drop_index('ix_reconciliation_results_audit_id', table_name='reconciliation_results')
    op.drop_table('reconciliation_results')
    op.drop_index('ix_invoice_extractions_invoice_id', table_name='invoice_extractions')
    op.drop_index('ix_invoice_extractions_document_id', table_name='invoice_extractions')
    op.drop_table('invoice_extractions')
    op.drop_index('ix_audit_corrections_invoice_id', table_name='audit_corrections')
    op.drop_index('ix_audit_corrections_audit_id', table_name='audit_corrections')
    op.drop_table('audit_corrections')
    op.drop_index('ix_ledger_po_item_invoice', table_name='invoice_line_ledger')
    op.drop_index('ix_ledger_po_item_id', table_name='invoice_line_ledger')
    op.drop_index('ix_ledger_invoice_id', table_name='invoice_line_ledger')
    op.drop_table('invoice_line_ledger')
    op.drop_index('ix_invoice_items_invoice_id', table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index('ix_invoice_documents_invoice_id', table_name='invoice_documents')
    op.drop_index('ix_invoice_documents_hash', table_name='invoice_documents')
    op.drop_table('invoice_documents')
    op.drop_index('ix_audits_status', table_name='audits')
    op.drop_index('ix_audits_purchase_order_id', table_name='audits')
    op.drop_index('ix_audits_invoice_id', table_name='audits')
    op.drop_table('audits')
    op.drop_index('ix_po_items_po_id', table_name='purchase_order_items')
    op.drop_table('purchase_order_items')
    op.drop_index('ix_invoices_vendor_name', table_name='invoices')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_purchase_order_id', table_name='invoices')
    op.drop_index('ix_invoices_po_number', table_name='invoices')
    op.drop_index('ix_invoices_invoice_number', table_name='invoices')
    op.drop_index('ix_invoices_dup_detection', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_purchase_orders_vendor_name', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_status', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_po_number', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
